use fenestra_ui_authoring::prototype::{
    AnchorKindV2, AuthoringDiagnosticKindV2, AuthoringFrontendV2, AuthoringLimitKindV2,
    AuthoringLimitsV1, DiagnosticLocationV2, FenSourceV1, GeneratedRustV2,
    REFERENCE_SEMANTIC_ARTIFACT_LIMITS_V1, canonical_rust_v2, canonical_semantics_v1,
    compile_fen_v1, emit_tokens_v1, emit_tokens_v2,
};
use fenestra_ui_ir::prototype::{SourceId, SourceSpan};
use proc_macro2::TokenStream;

use crate::support;

#[test]
fn emitted_tokens_are_a_deterministic_closed_ir_quadruple() {
    let (fen, ui) = support::compile_both();
    let expected = emit_tokens_v2(&fen, support::limits())
        .expect("reference quadruple should emit")
        .to_string();
    for compiled in [&fen, &fen, &ui, &ui] {
        let actual = emit_tokens_v2(compiled, support::limits())
            .expect("both frontends should emit")
            .to_string();
        assert_eq!(actual, expected);
    }

    let compact = compact(&expected);
    let constructors = [
        "::fenestra_ui_ir::prototype::SchemaManifest::new(",
        "::fenestra_ui_ir::prototype::ConstructionProgram::new(",
        "::fenestra_ui_ir::prototype::StyleProgram::new(",
        "::fenestra_ui_ir::prototype::SpatialProgramV2::new(",
    ];
    let positions = constructors.map(|constructor| {
        compact
            .find(constructor)
            .unwrap_or_else(|| panic!("missing emitted constructor {constructor}"))
    });
    assert!(positions.windows(2).all(|pair| pair[0] < pair[1]));
    assert!(compact.starts_with('(') && compact.ends_with(')'));
    let paths = compact.match_indices("fenestra_ui_ir").collect::<Vec<_>>();
    assert!(!paths.is_empty());
    for (start, _) in paths {
        assert_eq!(&compact[start - 2..start], "::");
        assert!(compact[start + "fenestra_ui_ir".len()..].starts_with("::prototype::"));
    }
    for forbidden in [
        "fenestra_ui_authoring",
        "CompiledAuthoringV2",
        "Resolved",
        "SourceMap",
        "scene",
        "checker",
    ] {
        assert!(!compact.contains(forbidden), "emission leaked {forbidden}");
    }
}

#[test]
fn canonical_rust_is_exactly_token_spelling_plus_one_ascii_lf() {
    let (fen, ui) = support::compile_both();
    let tokens = emit_tokens_v2(&fen, support::limits()).expect("tokens");
    let expected = format!("{tokens}\n");
    let outputs = [
        canonical(&fen),
        canonical(&fen),
        canonical(&ui),
        canonical(&ui),
    ];
    for output in outputs {
        assert_eq!(output.as_str(), expected);
        assert!(output.as_str().is_ascii());
        assert!(!output.as_str().contains('\r'));
        let body = output.as_str().strip_suffix('\n').expect("one final LF");
        assert!(!body.ends_with('\n'));
    }
}

#[test]
fn generated_rust_exact_limit_passes_and_one_under_is_document_anchored() {
    let (fen, ui) = support::compile_both();
    let measured = canonical(&fen).as_str().len();
    assert!(measured > 0);
    for (frontend, compiled) in [
        (AuthoringFrontendV2::Fen, &fen),
        (AuthoringFrontendV2::UiMacro, &ui),
    ] {
        let exact = canonical_rust_v2(compiled, support::limits_with_generated_rust(measured))
            .expect("exact generated byte limit must pass");
        assert_eq!(exact.as_str().len(), measured);
        let error = canonical_rust_v2(compiled, support::limits_with_generated_rust(measured - 1))
            .expect_err("one byte under must fail");
        assert_eq!(error.frontend(), frontend);
        assert_eq!(
            error.kind(),
            AuthoringDiagnosticKindV2::LimitExceeded(AuthoringLimitKindV2::GeneratedRustBytes)
        );
        let DiagnosticLocationV2::Anchored {
            logical,
            anchor_kind,
            physical,
        } = error.location()
        else {
            panic!("emission failure must use the document anchor");
        };
        assert_eq!(*logical, SourceSpan::bytes(SourceId::new(0), 0, 1));
        assert_eq!(*anchor_kind, AnchorKindV2::Document);
        match frontend {
            AuthoringFrontendV2::Fen => {
                assert_eq!(physical.source_id(), Some(support::SOURCE_ID));
                assert_eq!(physical.fen_byte_range(), Some((0, 6)));
            }
            AuthoringFrontendV2::UiMacro => {
                assert_eq!(physical.source_id(), None);
                assert_eq!(physical.fen_byte_range(), None);
            }
        }
    }
}

#[test]
fn format_one_tokens_and_semantic_bytes_remain_exactly_unchanged() {
    let compiled = compile_fen_v1(
        FenSourceV1::new(SourceId::new(95), support::V1_DOCUMENT.as_bytes()),
        v1_limits(),
    )
    .expect("the established V1 fixture must still compile");
    let tokens = emit_tokens_v1(&compiled, v1_limits()).expect("V1 tokens");
    let golden: TokenStream = include_str!("../fixtures/minimal_emitted_v1.rs")
        .parse()
        .expect("committed V1 golden must tokenize");
    assert_eq!(tokens.to_string(), golden.to_string());

    let artifact = canonical_semantics_v1(&compiled, REFERENCE_SEMANTIC_ARTIFACT_LIMITS_V1)
        .expect("V1 semantic artifact");
    assert_eq!(artifact.as_str(), V1_SEMANTICS);
}

fn canonical(compiled: &fenestra_ui_authoring::prototype::CompiledAuthoringV2) -> GeneratedRustV2 {
    canonical_rust_v2(compiled, support::limits()).expect("canonical Rust")
}

fn compact(source: &str) -> String {
    source
        .chars()
        .filter(|character| !character.is_ascii_whitespace())
        .collect()
}

const fn v1_limits() -> AuthoringLimitsV1 {
    AuthoringLimitsV1::new(8_192, 1_024, 32, 8, 8, 16, 8, 8, 16, 16, 8, 8, 64, 65_536)
}

const V1_SEMANTICS: &str = concat!(
    "fenestra-authoring-semantics|1|authoring-format=1|schema-format=1|",
    "construction-format=1|style-format=1|records=21\n",
    "record|0|document|span=0:1|format=1\n",
    "record|1|schema|span=1:2|namespace=9|revision=1\n",
    "record|2|component|span=2:3|order=0|name=panel|id=7\n",
    "record|3|property|span=3:4|component=7|order=0|name=visible|id=0|",
    "type=bool|default=bool:true|invalidates=paint\n",
    "record|4|property|span=4:5|component=7|order=1|name=width|id=1|",
    "type=scalar-i32|default=scalar-i32:-2|invalidates=layout,semantics\n",
    "record|5|property|span=5:6|component=7|order=2|name=color|id=2|",
    "type=rgba8|default=rgba8:1,2,3,255|invalidates=paint\n",
    "record|6|property|span=6:7|component=7|order=3|name=input|id=3|",
    "type=input-policy|default=input-policy:ignore|invalidates=hit-test\n",
    "record|7|construction|span=7:8|namespace=9|revision=1\n",
    "record|8|template|span=8:9|order=0|name=root|id=10|component=7\n",
    "record|9|initial-property|span=9:10|template=10|order=0|property=0|",
    "value=bool:false\n",
    "record|10|initial-property|span=10:11|template=10|order=1|property=1|",
    "value=scalar-i32:3\n",
    "record|11|initial-property|span=11:12|template=10|order=2|property=2|",
    "value=rgba8:4,5,6,255\n",
    "record|12|initial-property|span=12:13|template=10|order=3|property=3|",
    "value=input-policy:accept\n",
    "record|13|static-child|span=13:14|template=10|order=0|target=11\n",
    "record|14|region-child|span=14:15|template=10|order=1|region=5\n",
    "record|15|template|span=15:16|order=1|name=leaf|id=11|component=7\n",
    "record|16|template|span=16:17|order=2|name=cell|id=12|component=7\n",
    "record|17|region|span=17:18|order=0|name=rows|id=5|owner=10|",
    "repeat=12|invalidates=structure,layout\n",
    "record|18|initial-key|span=18:19|region=5|order=0|key=42\n",
    "record|19|style|span=19:20|namespace=9|revision=1\n",
    "record|20|style-assignment|span=20:21|order=0|target=11|property=2|",
    "value=rgba8:7,8,9,255\n",
);
