use fenestra_ui_layout::prototype::LayoutAxisV1::Column;

use super::support::{
    ExpectedCaseV1, dimension, expected_case, fixed_node, node, padding, record, viewport,
};

pub fn cases() -> Vec<ExpectedCaseV1> {
    vec![
        node_ceiling_case(),
        child_ceiling_case(),
        depth_ceiling_case(),
        registered_runtime_case(),
    ]
}

fn node_ceiling_case() -> ExpectedCaseV1 {
    expected_case(
        "node-ceiling",
        viewport(0, 0),
        vec![
            fixed_node(0, None, Column, 0, 0),
            fixed_node(1, Some(0), Column, 0, 0),
            fixed_node(2, Some(1), Column, 0, 0),
            fixed_node(3, Some(1), Column, 0, 0),
            fixed_node(4, Some(1), Column, 0, 0),
            fixed_node(5, Some(0), Column, 0, 0),
            fixed_node(6, Some(5), Column, 0, 0),
            fixed_node(7, Some(5), Column, 0, 0),
            fixed_node(8, Some(5), Column, 0, 0),
            fixed_node(9, Some(0), Column, 0, 0),
            fixed_node(10, Some(9), Column, 0, 0),
            fixed_node(11, Some(9), Column, 0, 0),
            fixed_node(12, Some(9), Column, 0, 0),
            fixed_node(13, Some(0), Column, 0, 0),
            fixed_node(14, Some(13), Column, 0, 0),
            fixed_node(15, Some(13), Column, 0, 0),
            fixed_node(16, Some(13), Column, 0, 0),
            fixed_node(17, Some(0), Column, 0, 0),
            fixed_node(18, Some(17), Column, 0, 0),
            fixed_node(19, Some(17), Column, 0, 0),
            fixed_node(20, Some(17), Column, 0, 0),
            fixed_node(21, Some(0), Column, 0, 0),
            fixed_node(22, Some(21), Column, 0, 0),
            fixed_node(23, Some(21), Column, 0, 0),
            fixed_node(24, Some(21), Column, 0, 0),
            fixed_node(25, Some(0), Column, 0, 0),
            fixed_node(26, Some(25), Column, 0, 0),
            fixed_node(27, Some(25), Column, 0, 0),
            fixed_node(28, Some(25), Column, 0, 0),
            fixed_node(29, Some(0), Column, 0, 0),
            fixed_node(30, Some(29), Column, 0, 0),
            fixed_node(31, Some(29), Column, 0, 0),
        ],
        vec![
            record(0, 0, 0, 0, 0),
            record(1, 0, 0, 0, 0),
            record(2, 0, 0, 0, 0),
            record(3, 0, 0, 0, 0),
            record(4, 0, 0, 0, 0),
            record(5, 0, 0, 0, 0),
            record(6, 0, 0, 0, 0),
            record(7, 0, 0, 0, 0),
            record(8, 0, 0, 0, 0),
            record(9, 0, 0, 0, 0),
            record(10, 0, 0, 0, 0),
            record(11, 0, 0, 0, 0),
            record(12, 0, 0, 0, 0),
            record(13, 0, 0, 0, 0),
            record(14, 0, 0, 0, 0),
            record(15, 0, 0, 0, 0),
            record(16, 0, 0, 0, 0),
            record(17, 0, 0, 0, 0),
            record(18, 0, 0, 0, 0),
            record(19, 0, 0, 0, 0),
            record(20, 0, 0, 0, 0),
            record(21, 0, 0, 0, 0),
            record(22, 0, 0, 0, 0),
            record(23, 0, 0, 0, 0),
            record(24, 0, 0, 0, 0),
            record(25, 0, 0, 0, 0),
            record(26, 0, 0, 0, 0),
            record(27, 0, 0, 0, 0),
            record(28, 0, 0, 0, 0),
            record(29, 0, 0, 0, 0),
            record(30, 0, 0, 0, 0),
            record(31, 0, 0, 0, 0),
        ],
    )
}

fn child_ceiling_case() -> ExpectedCaseV1 {
    expected_case(
        "child-ceiling",
        viewport(0, 0),
        vec![
            fixed_node(0, None, Column, 0, 0),
            fixed_node(1, Some(0), Column, 0, 0),
            fixed_node(2, Some(0), Column, 0, 0),
            fixed_node(3, Some(0), Column, 0, 0),
            fixed_node(4, Some(0), Column, 0, 0),
            fixed_node(5, Some(0), Column, 0, 0),
            fixed_node(6, Some(0), Column, 0, 0),
            fixed_node(7, Some(0), Column, 0, 0),
            fixed_node(8, Some(0), Column, 0, 0),
            fixed_node(9, Some(0), Column, 0, 0),
            fixed_node(10, Some(0), Column, 0, 0),
            fixed_node(11, Some(0), Column, 0, 0),
            fixed_node(12, Some(0), Column, 0, 0),
            fixed_node(13, Some(0), Column, 0, 0),
            fixed_node(14, Some(0), Column, 0, 0),
            fixed_node(15, Some(0), Column, 0, 0),
            fixed_node(16, Some(0), Column, 0, 0),
        ],
        vec![
            record(0, 0, 0, 0, 0),
            record(1, 0, 0, 0, 0),
            record(2, 0, 0, 0, 0),
            record(3, 0, 0, 0, 0),
            record(4, 0, 0, 0, 0),
            record(5, 0, 0, 0, 0),
            record(6, 0, 0, 0, 0),
            record(7, 0, 0, 0, 0),
            record(8, 0, 0, 0, 0),
            record(9, 0, 0, 0, 0),
            record(10, 0, 0, 0, 0),
            record(11, 0, 0, 0, 0),
            record(12, 0, 0, 0, 0),
            record(13, 0, 0, 0, 0),
            record(14, 0, 0, 0, 0),
            record(15, 0, 0, 0, 0),
            record(16, 0, 0, 0, 0),
        ],
    )
}

fn depth_ceiling_case() -> ExpectedCaseV1 {
    expected_case(
        "depth-ceiling",
        viewport(0, 0),
        vec![
            fixed_node(0, None, Column, 0, 0),
            fixed_node(1, Some(0), Column, 0, 0),
            fixed_node(2, Some(1), Column, 0, 0),
            fixed_node(3, Some(2), Column, 0, 0),
            fixed_node(4, Some(3), Column, 0, 0),
            fixed_node(5, Some(4), Column, 0, 0),
            fixed_node(6, Some(5), Column, 0, 0),
            fixed_node(7, Some(6), Column, 0, 0),
        ],
        vec![
            record(0, 0, 0, 0, 0),
            record(1, 0, 0, 0, 0),
            record(2, 0, 0, 0, 0),
            record(3, 0, 0, 0, 0),
            record(4, 0, 0, 0, 0),
            record(5, 0, 0, 0, 0),
            record(6, 0, 0, 0, 0),
            record(7, 0, 0, 0, 0),
        ],
    )
}

fn registered_runtime_case() -> ExpectedCaseV1 {
    expected_case(
        "registered-runtime-fixture",
        viewport(120, 90),
        vec![
            node(
                0,
                None,
                Column,
                dimension(0, 100, 100),
                dimension(0, 80, 80),
                padding(0, 0, 0, 0),
                0,
            ),
            node(
                1,
                Some(0),
                Column,
                dimension(0, 80, 100),
                dimension(0, 50, 50),
                padding(0, 0, 0, 0),
                0,
            ),
            node(
                2,
                Some(1),
                Column,
                dimension(0, 30, 80),
                dimension(0, 10, 10),
                padding(0, 0, 0, 0),
                0,
            ),
            node(
                3,
                Some(1),
                Column,
                dimension(0, 40, 80),
                dimension(0, 12, 12),
                padding(0, 0, 0, 0),
                0,
            ),
            node(
                4,
                Some(1),
                Column,
                dimension(0, 40, 80),
                dimension(0, 12, 12),
                padding(0, 0, 0, 0),
                0,
            ),
        ],
        vec![
            record(0, 0, 0, 100, 80),
            record(1, 0, 0, 80, 50),
            record(2, 0, 0, 30, 10),
            record(3, 0, 10, 40, 12),
            record(4, 0, 22, 40, 12),
        ],
    )
}
