use fenestra_ui_authoring::prototype::{
    AuthoringDiagnosticKindV1, AuthoringLimitKindV1, AuthoringLimitsV1, compile_ui_v1,
    diagnostic_tokens_v1, emit_tokens_v1, expand_ui_v1,
};
use proc_macro2::{Delimiter, Punct, Spacing, TokenStream, TokenTree};

const DOCUMENT: &str = "format 1;
schema namespace 1 revision 1 {
  component c = 0 {
    property p = 0: scalar_i32 = 0 invalidates [layout];
  }
}
construction {
  template root = 0: c {
    child region rows;
  }
  template cell = 1: c {}
  region rows = 0 owner root repeat cell keys [] invalidates [structure];
}
style {}
";

#[test]
fn valid_ui_expansion_is_exactly_the_shared_compile_and_emit_pipeline() {
    let limits = limits(65_536);
    let input = ui_tokens(DOCUMENT);
    let compiled = compile_ui_v1(input.clone(), limits)
        .expect("the valid UI document should compile through the shared frontend");
    let expected = emit_tokens_v1(&compiled, limits)
        .expect("the compiled UI document should emit through the shared emitter");

    let expanded = expand_ui_v1(input, limits);

    assert_eq!(expanded.to_string(), expected.to_string());
    assert!(!expanded.to_string().contains("compile_error"));
}

#[test]
fn physical_anchored_and_generated_failures_expand_to_one_closed_compile_error() {
    let generous = limits(65_536);

    let physical_input = unsupported_punctuation();
    let physical = compile_ui_v1(physical_input.clone(), generous)
        .expect_err("unsupported punctuation should fail before parsing");
    assert_eq!(physical.kind(), AuthoringDiagnosticKindV1::UnsupportedToken);
    assert_error_expansion(
        "physical",
        physical,
        expand_ui_v1(physical_input, generous),
        "unsupported-token",
        &["+"],
    );

    let secret_name = "secret_missing_component";
    let anchored_source = DOCUMENT.replacen(
        "template root = 0: c {",
        &format!("template root = 0: {secret_name} {{"),
        1,
    );
    let anchored_input = ui_tokens(&anchored_source);
    let anchored = compile_ui_v1(anchored_input.clone(), generous)
        .expect_err("an unknown component should fail at its semantic anchor");
    assert_eq!(
        anchored.kind(),
        AuthoringDiagnosticKindV1::UnknownComponentName
    );
    assert_error_expansion(
        "anchored",
        anchored,
        expand_ui_v1(anchored_input, generous),
        "unknown-component-name",
        &[secret_name],
    );

    let generated_limits = limits(0);
    let generated_input = ui_tokens(DOCUMENT);
    let compiled = compile_ui_v1(generated_input.clone(), generated_limits)
        .expect("generated-byte limits should not apply before emission");
    let generated = emit_tokens_v1(&compiled, generated_limits)
        .expect_err("zero generated bytes should reject the emitted expression");
    assert_eq!(
        generated.kind(),
        AuthoringDiagnosticKindV1::LimitExceeded(AuthoringLimitKindV1::GeneratedRustBytes)
    );
    assert_error_expansion(
        "generated",
        generated,
        expand_ui_v1(generated_input, generated_limits),
        "limit-exceeded(generated-rust-bytes)",
        &[],
    );
}

fn assert_error_expansion(
    name: &str,
    error: fenestra_ui_authoring::prototype::AuthoringDiagnosticV1,
    expanded: TokenStream,
    expected_code: &str,
    case_payloads: &[&str],
) {
    let direct = diagnostic_tokens_v1(error);
    assert_single_compile_error(name, &direct, expected_code, case_payloads);
    assert_single_compile_error(name, &expanded, expected_code, case_payloads);
    assert_eq!(
        expanded.to_string(),
        direct.to_string(),
        "{name} expansion diverged from diagnostic_tokens_v1"
    );
}

fn assert_single_compile_error(
    name: &str,
    tokens: &TokenStream,
    expected_code: &str,
    case_payloads: &[&str],
) {
    let trees = tokens.clone().into_iter().collect::<Vec<_>>();
    assert_eq!(trees.len(), 4, "{name} should emit one macro invocation");

    let TokenTree::Ident(macro_name) = &trees[0] else {
        panic!("{name} should start with the compile_error identifier");
    };
    assert_eq!(macro_name.to_string(), "compile_error");

    let TokenTree::Punct(bang) = &trees[1] else {
        panic!("{name} compile_error should have a bang");
    };
    assert_eq!(bang.as_char(), '!');

    let TokenTree::Group(arguments) = &trees[2] else {
        panic!("{name} compile_error should have one argument group");
    };
    assert_eq!(arguments.delimiter(), Delimiter::Parenthesis);
    let arguments = arguments.stream().into_iter().collect::<Vec<_>>();
    assert_eq!(arguments.len(), 1, "{name} should emit one message");
    let TokenTree::Literal(message) = &arguments[0] else {
        panic!("{name} compile_error message should be a string literal");
    };
    assert_eq!(message.to_string(), format!("{expected_code:?}"));

    let TokenTree::Punct(semicolon) = &trees[3] else {
        panic!("{name} compile_error should end in a semicolon");
    };
    assert_eq!(semicolon.as_char(), ';');

    let spelling = tokens.to_string();
    assert_eq!(spelling.matches("compile_error").count(), 1);
    for forbidden in [
        "/home/",
        "C:\\",
        ".fen",
        "PhysicalOrigin",
        "SourceId",
        "AuthoringDiagnostic",
    ]
    .into_iter()
    .chain(case_payloads.iter().copied())
    {
        assert!(
            !spelling.contains(forbidden),
            "{name} diagnostic leaked `{forbidden}`"
        );
    }
}

fn unsupported_punctuation() -> TokenStream {
    TokenStream::from(TokenTree::Punct(Punct::new('+', Spacing::Alone)))
}

fn ui_tokens(source: &str) -> TokenStream {
    source
        .parse()
        .unwrap_or_else(|error| panic!("test UI source should tokenize: {error}"))
}

const fn limits(generated_rust_bytes: usize) -> AuthoringLimitsV1 {
    AuthoringLimitsV1::new(
        8_192,
        1_024,
        32,
        8,
        8,
        16,
        8,
        8,
        16,
        16,
        8,
        8,
        64,
        generated_rust_bytes,
    )
}
