[package]
name = "fenestra-ui-authoring"
description = "Experimental host-side typed authoring compiler for Fenestra"
version.workspace = true
edition.workspace = true
publish.workspace = true
repository.workspace = true

[dependencies]
fenestra-ui-ir.workspace = true

[dev-dependencies]
proc-macro2 = "=1.0.107"

[lints]
workspace = true
