use crate::limits_v2::AuthoringLimitsV2;

/// Inclusive resource limits for one format-3 compilation.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct Limits {
    pub(super) source_bytes: usize,
    pub(super) elements: usize,
    pub(super) nesting_depth: usize,
    pub(super) tokens: usize,
    pub(super) generated_bytes: usize,
}

impl Limits {
    /// Sets source bytes, elements, delimiter depth, tokens, and generated bytes.
    /// Generated bytes include the final line feed. Depth counts all delimiters.
    #[must_use]
    pub const fn new(
        source_bytes: usize,
        elements: usize,
        nesting_depth: usize,
        tokens: usize,
        generated_bytes: usize,
    ) -> Self {
        Self {
            source_bytes,
            elements,
            nesting_depth,
            tokens,
            generated_bytes,
        }
    }

    /// Returns the maximum number of bytes in one `.fen` input.
    #[must_use]
    pub const fn source_bytes(self) -> usize {
        self.source_bytes
    }

    /// Returns the maximum number of named elements.
    #[must_use]
    pub const fn elements(self) -> usize {
        self.elements
    }

    /// Returns the maximum delimiter nesting depth.
    #[must_use]
    pub const fn nesting_depth(self) -> usize {
        self.nesting_depth
    }

    /// Returns the maximum number of flattened frontend tokens.
    #[must_use]
    pub const fn tokens(self) -> usize {
        self.tokens
    }

    /// Returns the maximum generated Rust bytes, including the final line feed.
    #[must_use]
    pub const fn generated_bytes(self) -> usize {
        self.generated_bytes
    }

    pub(super) fn frontend(self) -> AuthoringLimitsV2 {
        let mut values = [0; 28];
        values[0] = self.source_bytes;
        values[1] = self.tokens;
        values[2] = usize::MAX;
        values[3] = self.nesting_depth;
        AuthoringLimitsV2::new(values)
    }
}

impl Default for Limits {
    fn default() -> Self {
        Self::new(256 * 1024, 1024, 64, 65_536, 1024 * 1024)
    }
}
